src/test/resources/application.yml

> #8 
> test폴더 application.yml 파일 datasource부분 절대건드리지말기
>

feat: 찐 파일업로드 구현

---

build.gradle
src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/file/FileStoreService.java
src/main/java/com/kb/zipkim/domain/prop/file/FileStoreServiceAWS.java
src/main/java/com/kb/zipkim/domain/prop/file/FileStoreServicePC.java
src/main/java/com/kb/zipkim/global/config/S3config.java
src/test/resources/application.yml

> #8 
> 환경별 파일업로드서비스 분리 및 S3추가
>

Feat: S3설정 추가

---

.gitignore
build.gradle
src/main/java/com/kb/zipkim/TestController.java
src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/domain/prop/file/FileStoreService.java
src/main/java/com/kb/zipkim/domain/prop/file/FileStoreServiceAWS.java
src/main/java/com/kb/zipkim/domain/prop/file/FileStoreServicePC.java
src/main/java/com/kb/zipkim/domain/prop/file/UploadFile.java
src/main/java/com/kb/zipkim/domain/prop/repository/PropertyRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/domain/register/register/Registered.java
src/main/java/com/kb/zipkim/global/config/S3config.java
src/main/resources/application.properties
src/test/java/com/kb/zipkim/ZipkimApplicationTests.java
src/test/java/com/kb/zipkim/domain/prop/repository/PropertyRepositoryTest.java
src/test/resources/application.yml

Feat aws파일저장서비스 구현

---

build.gradle

Fix: build.gradle수정

---

src/main/java/com/kb/zipkim/ZipkimApplication.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/global/BaseEntity.java

> #8 
> 매물등록, 수정시 등록날짜 수정날짜 추가 기능 구현
>

feat: 매물등록시 등록날짜추가 기능 구현

---

src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java

> #8 
> 이미지 없어도 등록되게 수정했습니다.
>

fix: 이미지 없을시 등록안되는거 수정

---

src/main/java/com/kb/zipkim/ZipkimApplication.java
src/main/java/com/kb/zipkim/global/config/RedisConfig.java
src/test/resources/application.yml

feat: Redis 설정추가

---

src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/LocationWithRadius.java
src/main/java/com/kb/zipkim/domain/prop/dto/NearByProp.java
src/main/java/com/kb/zipkim/domain/prop/file/UploadFile.java
src/main/java/com/kb/zipkim/domain/prop/repository/PropertyRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/global/config/RedisConfig.java

> 
> redis 설정 추가
> 주변 매물찾기 일부 구현
>

feat: redis설정 추가 및 주변 매물찾기 일부구현

---

src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java
src/main/java/com/kb/zipkim/domain/prop/entity/Complex.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/domain/prop/repository/ComplexRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java

> 기존 매물의 위치정보 주소명을 별도의 건물 클래스(Complex) 와 테이블로 분리했습니다.
>

Feat 매물 건물 분리

---

src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/NearByComplex.java
src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java
src/main/java/com/kb/zipkim/domain/prop/entity/Complex.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/domain/prop/redis/CacheWarmingService.java
src/main/java/com/kb/zipkim/domain/prop/repository/PropertyRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java

> #8 
> 건물에 건물명, 매물수, 전세 매매 총합추가
>

feat: 건물 내 총 매물수, 전세,매매 총 합 추가

---

src/main/java/com/kb/zipkim/domain/prop/dto/NearByComplex.java
src/main/java/com/kb/zipkim/domain/prop/redis/CacheWarmingService.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java

> #28 
> 위,경도, 반경으로 주변 단지정보 제공, controller 수정해서 단지종류별로 필터되게 해야할듯?
>

feat: NearByComplex에 단지 타입도 추가

---

src/main/java/com/kb/zipkim/domain/prop/ComplexListResponse.java
src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java

> #28 
> 지도 중심좌표에서 일정반경내에 있는 단지(매물이있는) 목록 제공
>

feat: 단지List response entity 추가

---

build.gradle

feat: query-dsl설정 추가

---

build.gradle
src/main/java/com/kb/zipkim/ZipkimApplication.java

> #35 
> spring boot 버전 3.2로 다운그레이드
>

fix: spring boot버전 다운그레이드, 필요없는설정삭제

---

src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java
src/main/java/com/kb/zipkim/domain/prop/dto/SearchResponse.java
src/main/java/com/kb/zipkim/domain/prop/repository/ComplexQueryRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/global/config/QueryDslConfig.java
src/test/java/com/kb/zipkim/domain/prop/repository/PropertyRepositoryTest.java

> 
> 단지검색Api 추가, 함수명 변경 findNearProp->findNearComplexes
>

feat: 단지 검색기능 추가

---

src/test/java/com/kb/zipkim/domain/prop/repository/PropertyRepositoryTest.java

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>

fix: test code 수정

---

src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/ComplexInfo.java
src/main/java/com/kb/zipkim/domain/prop/dto/SimplePropInfo.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/domain/prop/repository/ComplexPropQueryRepository.java
src/main/java/com/kb/zipkim/domain/prop/repository/PropertyRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/global/exception/ErrorResponse.java

> #40 
> 아이콘 클릭시 단지정보, 단지내 매물리스트 정보 api 구현 
>

feat: 단지 내 매물리스트정보  구현

---

src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java
src/main/java/com/kb/zipkim/domain/prop/dto/SimplePropInfo.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java

feat: 매물에 상세주소 추가

---

src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/PropInfo.java
src/main/java/com/kb/zipkim/domain/prop/repository/ComplexPropQueryRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java

> 
> 매물 상세정보 아직 미완성.
로그인기능 완성시 개선필요
>

Feat: 매물상세정보 (미완성)

---

src/main/java/com/kb/zipkim/domain/login/config/CorsMvcConfig.java
src/main/java/com/kb/zipkim/domain/login/controller/LoginController.java
src/main/java/com/kb/zipkim/domain/login/controller/UserController.java
src/main/java/com/kb/zipkim/domain/login/dto/AccessToken.java
src/main/java/com/kb/zipkim/domain/login/dto/UserDTO.java
src/main/java/com/kb/zipkim/domain/login/entity/UserEntity.java
src/main/java/com/kb/zipkim/domain/login/jwt/JWTFilter.java
src/main/java/com/kb/zipkim/domain/login/jwt/JWTUtil.java
src/main/java/com/kb/zipkim/domain/login/oauth2/CustomSuccessHandler.java
src/main/java/com/kb/zipkim/domain/login/service/CustomOAuth2UserService.java

fix: db에 정보 추가되게 변경
fix: cookie가 null일 때 예외처리
> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
>

feat: 로그인 정보 확인을 위한 컨트롤러

---

src/main/java/com/kb/zipkim/domain/complex/controller/ComplexController.java
src/main/java/com/kb/zipkim/domain/complex/dto/ComplexInfo.java
src/main/java/com/kb/zipkim/domain/complex/dto/LocationWithRadius.java
src/main/java/com/kb/zipkim/domain/complex/dto/NearByComplex.java
src/main/java/com/kb/zipkim/domain/complex/dto/SearchResponse.java
src/main/java/com/kb/zipkim/domain/complex/entity/Complex.java
src/main/java/com/kb/zipkim/domain/complex/repository/ComplexRepository.java
src/main/java/com/kb/zipkim/domain/complex/service/ComplexService.java
src/main/java/com/kb/zipkim/domain/prop/Response.java
src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/domain/prop/repository/ComplexPropQueryRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/global/redis/CacheWarmingService.java

> prop패키지에 있던 Complex 관련 class 분리했습니다.
>

refactor: complex도메인 분리

---

src/main/java/com/kb/zipkim/domain/complex/entity/Complex.java
src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/domain/register/entity/Registered.java
src/main/java/com/kb/zipkim/domain/register/repository/RegisteredRepository.java

> 단지종류별 등록로직수정 , 매물 등기 1:1관계로 변경 
>

fix: 단지종류별 등록로직 수정

---

src/main/java/com/kb/zipkim/domain/area/dto/AreaInfo.java
src/main/java/com/kb/zipkim/domain/area/entity/Area.java
src/main/java/com/kb/zipkim/domain/area/repository/AreaRepository.java
src/main/java/com/kb/zipkim/domain/complex/controller/ComplexController.java
src/main/java/com/kb/zipkim/domain/complex/dto/ComplexInfo.java
src/main/java/com/kb/zipkim/domain/complex/service/ComplexService.java

> #58 
>  area엔티티 추가, 간략한 단지정보 api추가
>

feat: area엔티티 추가, 간략한 단지정보 api추가

---

src/main/java/com/kb/zipkim/domain/transaction/TransactionType.java
src/main/java/com/kb/zipkim/domain/transaction/controller/TransactionHistoryController.java
src/main/java/com/kb/zipkim/domain/transaction/dto/TransactionResponse.java
src/main/java/com/kb/zipkim/domain/transaction/entity/TransactionHistory.java
src/main/java/com/kb/zipkim/domain/transaction/repository/TransactionHistoryRepository.java
src/main/java/com/kb/zipkim/domain/transaction/service/TransactionHistoryService.java

feat: 거래내역 api추가

---

src/main/java/com/kb/zipkim/domain/login/config/SecurityConfig.java
src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/DetailPropInfo.java
src/main/java/com/kb/zipkim/domain/prop/entity/Property.java
src/main/java/com/kb/zipkim/domain/prop/repository/ComplexPropQueryRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/domain/transaction/repository/TransactionHistoryRepository.java
src/main/java/com/kb/zipkim/domain/transaction/service/TransactionHistoryService.java

fix: 매물등록 수정

---

src/main/java/com/kb/zipkim/domain/login/config/SecurityConfig.java

fix: addFilter(jwtFilter) 주석

---

src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/global/exception/AuthException.java
src/main/java/com/kb/zipkim/global/exception/ExceptionCode.java
src/main/java/com/kb/zipkim/global/exception/ExceptionHandlerAdvice.java

feat: 전역예외처리 추가

---

src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/DetailPropInfo.java
src/main/java/com/kb/zipkim/domain/prop/dto/PropImage.java
src/main/java/com/kb/zipkim/domain/prop/repository/ComplexPropQueryRepository.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/domain/register/dto/RegisterResponse.java
src/main/java/com/kb/zipkim/global/exception/ExceptionHandlerAdvice.java

feat: 매물상세보기api구현

---

src/main/java/com/kb/zipkim/domain/prop/dto/DetailPropInfo.java

feat: 매물상세보기에 상세주소추가

---

build.gradle
src/main/java/com/kb/zipkim/domain/prop/controller/PropertyController.java
src/main/java/com/kb/zipkim/domain/prop/dto/PropRegisterForm.java
src/main/java/com/kb/zipkim/domain/prop/service/PropertyService.java
src/main/java/com/kb/zipkim/global/exception/ExceptionHandlerAdvice.java

feat: 매물등록시예외처리 추가

---

src/main/java/com/kb/zipkim/domain/login/config/SecurityConfig.java

Reverts zipkim8080/zipkim-server#70

Revert "필터해제"
